### ISSUE TITLE
Remove la_rsync in umi blocks

### ISSUE THREAD

**Issue by aolofsson** [zeroasiccorp/umi#133]
Reset should not be used to gate control signals, this is not good practice from a wakeup/sta perspective. Let's find another solution.

/home/aolofsson/work/zeroasic/umi/umi/umi/rtl/umi_crossbar.v:   la_rsync la_rsync(.nrst_out          (ready_gated),
/home/aolofsson/work/zeroasic/umi/umi/umi/rtl/umi_endpoint.v:   la_rsync la_rsync(.nrst_out          (ready_gated),
/home/aolofsson/work/zeroasic/umi/umi/umi/rtl/umi_fifo_flex.v:   la_drsync la_drsync_i (

**Comment by azaidy** [comment]
Resolved in #173
